name: BUILD & TEST

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Unit Tests
      run: npm run test
    - name: Build
      run: npm run build --if-present
